# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cVBFAUKnvuSFa2Kt-QUB-7s4AP5AvlWR
"""

primeiro_numero = float(input('Digite o primeiro número: '))
segundo_numero = float(input('Digite o segundo número: '))

while True:

  print('\n1. Soma\n2. Subtração\n3. Multiplicação\n4. Divisão\n5. Sair')

  operacao = input('Digite o número correspondente a operação a ser realizada: ')

  if operacao == '1':
    resultado_operacao = primeiro_numero + segundo_numero
  elif operacao == '2':
    resultado_operacao = primeiro_numero - segundo_numero
  elif operacao == '3':
    resultado_operacao = primeiro_numero * segundo_numero
  elif operacao == '4':

    if segundo_numero == 0:
      print('Não é possível dividir por zero!')
      continue

    resultado_operacao = primeiro_numero / segundo_numero

  elif operacao == '5':
    print('\nObrigada por utilizar o programa, até a próxima!')
    break

  else:
    print('Operação inválida!')
    continue

  print('O Resultado da operação é:', resultado_operacao)